// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuskelMat_backend.Models;

#nullable disable

namespace MuskelMat_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220520074309_TestData")]
    partial class TestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("MuskelMat_backend.Models.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipesId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MuskelMat_backend.Models.Recipes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kcal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Protein")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kcal = 565,
                            MealType = "Lunch Middag",
                            Name = "Köttbullar i tomatsås med rostade grönsaker",
                            Protein = 28
                        },
                        new
                        {
                            Id = 2,
                            Kcal = 625,
                            MealType = "Lunch Middag",
                            Name = "Kalkonfilépasta med paprikapesto",
                            Protein = 38
                        },
                        new
                        {
                            Id = 3,
                            Kcal = 553,
                            MealType = "Lunch Middag",
                            Name = "Kotlett med äpple och ingefära",
                            Protein = 37
                        },
                        new
                        {
                            Id = 4,
                            Kcal = 529,
                            MealType = "Lunch Middag",
                            Name = "Renskavsgryta med gröna ärtor",
                            Protein = 30
                        });
                });

            modelBuilder.Entity("MuskelMat_backend.Models.Ingredients", b =>
                {
                    b.HasOne("MuskelMat_backend.Models.Recipes", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuskelMat_backend.Models.Recipes", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
