// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuskelMat_backend.Models;

#nullable disable

namespace MuskelMat_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("MuskelMat_backend.Models.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipesId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pasta",
                            RecipesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tomatsås",
                            RecipesId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rostade grönsaker",
                            RecipesId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Köttbullar",
                            RecipesId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rödlök",
                            RecipesId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kalkonbröst",
                            RecipesId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Snackmorötter",
                            RecipesId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pasta (Fusilli)",
                            RecipesId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Matlagningsgrädde",
                            RecipesId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pesto paprika",
                            RecipesId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Vitlök",
                            RecipesId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Rött äpple",
                            RecipesId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ris",
                            RecipesId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Gul lök",
                            RecipesId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ingefära",
                            RecipesId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Soja",
                            RecipesId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Fläskkotletter",
                            RecipesId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Plommontomater",
                            RecipesId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Morötter",
                            RecipesId = 4
                        },
                        new
                        {
                            Id = 20,
                            Name = "Gul lök",
                            RecipesId = 4
                        },
                        new
                        {
                            Id = 21,
                            Name = "Renskav",
                            RecipesId = 4
                        },
                        new
                        {
                            Id = 22,
                            Name = "Vitlök",
                            RecipesId = 4
                        },
                        new
                        {
                            Id = 23,
                            Name = "Soja",
                            RecipesId = 4
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ris",
                            RecipesId = 4
                        },
                        new
                        {
                            Id = 25,
                            Name = "Vispgrädde",
                            RecipesId = 4
                        },
                        new
                        {
                            Id = 26,
                            Name = "Matyoghurt",
                            RecipesId = 5
                        },
                        new
                        {
                            Id = 27,
                            Name = "Köttbullar",
                            RecipesId = 5
                        },
                        new
                        {
                            Id = 28,
                            Name = "Pitabröd",
                            RecipesId = 5
                        },
                        new
                        {
                            Id = 29,
                            Name = "Vitlök",
                            RecipesId = 5
                        },
                        new
                        {
                            Id = 30,
                            Name = "Blandsallad",
                            RecipesId = 5
                        },
                        new
                        {
                            Id = 31,
                            Name = "Mynta",
                            RecipesId = 5
                        },
                        new
                        {
                            Id = 32,
                            Name = "Citronjuice",
                            RecipesId = 5
                        },
                        new
                        {
                            Id = 33,
                            Name = "Couscous",
                            RecipesId = 6
                        },
                        new
                        {
                            Id = 34,
                            Name = "Kebabspett",
                            RecipesId = 6
                        },
                        new
                        {
                            Id = 35,
                            Name = "Piccolinitomater",
                            RecipesId = 6
                        },
                        new
                        {
                            Id = 36,
                            Name = "Persilja, färsk",
                            RecipesId = 6
                        },
                        new
                        {
                            Id = 37,
                            Name = "Babyspenat",
                            RecipesId = 6
                        },
                        new
                        {
                            Id = 38,
                            Name = "Rödbetshummus",
                            RecipesId = 6
                        },
                        new
                        {
                            Id = 39,
                            Name = "Färdig potatisgratäng",
                            RecipesId = 7
                        },
                        new
                        {
                            Id = 40,
                            Name = "Cosmopolitansallad",
                            RecipesId = 7
                        },
                        new
                        {
                            Id = 41,
                            Name = "Rödlök",
                            RecipesId = 7
                        },
                        new
                        {
                            Id = 42,
                            Name = "Rödvinsvinäger",
                            RecipesId = 7
                        },
                        new
                        {
                            Id = 43,
                            Name = "Dijonsenap",
                            RecipesId = 7
                        },
                        new
                        {
                            Id = 44,
                            Name = "Lövbiff",
                            RecipesId = 7
                        },
                        new
                        {
                            Id = 45,
                            Name = "Torskfilé",
                            RecipesId = 8
                        },
                        new
                        {
                            Id = 46,
                            Name = "Gröna linser",
                            RecipesId = 8
                        },
                        new
                        {
                            Id = 47,
                            Name = "Soltorkade tomater",
                            RecipesId = 8
                        },
                        new
                        {
                            Id = 48,
                            Name = "Citron",
                            RecipesId = 8
                        },
                        new
                        {
                            Id = 49,
                            Name = "Basilika",
                            RecipesId = 8
                        },
                        new
                        {
                            Id = 50,
                            Name = "Olivolja",
                            RecipesId = 8
                        },
                        new
                        {
                            Id = 51,
                            Name = "Passerade tomater",
                            RecipesId = 9
                        },
                        new
                        {
                            Id = 52,
                            Name = "Oregano",
                            RecipesId = 9
                        },
                        new
                        {
                            Id = 53,
                            Name = "Kärsbärstomater",
                            RecipesId = 9
                        },
                        new
                        {
                            Id = 54,
                            Name = "Färdig pizzadeg",
                            RecipesId = 9
                        },
                        new
                        {
                            Id = 55,
                            Name = "Västerbottenost",
                            RecipesId = 9
                        },
                        new
                        {
                            Id = 56,
                            Name = "Varmrökt lax",
                            RecipesId = 9
                        },
                        new
                        {
                            Id = 57,
                            Name = "Alaska pollock",
                            RecipesId = 10
                        },
                        new
                        {
                            Id = 58,
                            Name = "Färsk pepparrot",
                            RecipesId = 10
                        },
                        new
                        {
                            Id = 59,
                            Name = "Matlagningsgrädde",
                            RecipesId = 10
                        },
                        new
                        {
                            Id = 60,
                            Name = "Fiskbuljongtärning",
                            RecipesId = 10
                        },
                        new
                        {
                            Id = 61,
                            Name = "Ris",
                            RecipesId = 10
                        },
                        new
                        {
                            Id = 62,
                            Name = "Mangoldskott",
                            RecipesId = 10
                        },
                        new
                        {
                            Id = 63,
                            Name = "Kvarg",
                            RecipesId = 11
                        },
                        new
                        {
                            Id = 64,
                            Name = "Blåbär",
                            RecipesId = 11
                        },
                        new
                        {
                            Id = 65,
                            Name = "Hallon",
                            RecipesId = 11
                        },
                        new
                        {
                            Id = 66,
                            Name = "Havregryn",
                            RecipesId = 12
                        },
                        new
                        {
                            Id = 67,
                            Name = "Proteinpulver",
                            RecipesId = 12
                        },
                        new
                        {
                            Id = 68,
                            Name = "Jordnötssmör",
                            RecipesId = 12
                        },
                        new
                        {
                            Id = 69,
                            Name = "Mjölk",
                            RecipesId = 12
                        },
                        new
                        {
                            Id = 70,
                            Name = "Ägg",
                            RecipesId = 13
                        },
                        new
                        {
                            Id = 71,
                            Name = "Bacon",
                            RecipesId = 13
                        },
                        new
                        {
                            Id = 72,
                            Name = "Mellanmjölk",
                            RecipesId = 13
                        },
                        new
                        {
                            Id = 73,
                            Name = "Ägg",
                            RecipesId = 14
                        },
                        new
                        {
                            Id = 74,
                            Name = "Makrill i tomatsås",
                            RecipesId = 14
                        },
                        new
                        {
                            Id = 75,
                            Name = "Mjölk",
                            RecipesId = 15
                        },
                        new
                        {
                            Id = 76,
                            Name = "Ägg",
                            RecipesId = 15
                        },
                        new
                        {
                            Id = 77,
                            Name = "Vetemjöl",
                            RecipesId = 15
                        },
                        new
                        {
                            Id = 78,
                            Name = "Proteinpulver med chokladsmak",
                            RecipesId = 15
                        },
                        new
                        {
                            Id = 79,
                            Name = "Kakao",
                            RecipesId = 15
                        },
                        new
                        {
                            Id = 80,
                            Name = "Keso",
                            RecipesId = 16
                        },
                        new
                        {
                            Id = 81,
                            Name = "Äpple",
                            RecipesId = 16
                        },
                        new
                        {
                            Id = 82,
                            Name = "Kanel",
                            RecipesId = 16
                        },
                        new
                        {
                            Id = 83,
                            Name = "Lättmjölk",
                            RecipesId = 17
                        },
                        new
                        {
                            Id = 84,
                            Name = "Banan",
                            RecipesId = 17
                        },
                        new
                        {
                            Id = 85,
                            Name = "Havregryn",
                            RecipesId = 17
                        },
                        new
                        {
                            Id = 86,
                            Name = "Proteinpulver med chokladsmak",
                            RecipesId = 17
                        },
                        new
                        {
                            Id = 87,
                            Name = "Ägg",
                            RecipesId = 18
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kalkonpålägg",
                            RecipesId = 18
                        },
                        new
                        {
                            Id = 89,
                            Name = "Babyspenat",
                            RecipesId = 18
                        },
                        new
                        {
                            Id = 90,
                            Name = "Avokado",
                            RecipesId = 18
                        },
                        new
                        {
                            Id = 91,
                            Name = "Tomat",
                            RecipesId = 18
                        },
                        new
                        {
                            Id = 92,
                            Name = "Mellanmjölk",
                            RecipesId = 19
                        },
                        new
                        {
                            Id = 93,
                            Name = "Proteinpulver",
                            RecipesId = 19
                        },
                        new
                        {
                            Id = 94,
                            Name = "Ägg",
                            RecipesId = 20
                        },
                        new
                        {
                            Id = 95,
                            Name = "Äpple",
                            RecipesId = 21
                        },
                        new
                        {
                            Id = 96,
                            Name = "Keso",
                            RecipesId = 22
                        },
                        new
                        {
                            Id = 97,
                            Name = "Naturell lättyoghurt",
                            RecipesId = 22
                        },
                        new
                        {
                            Id = 98,
                            Name = "Banan",
                            RecipesId = 22
                        },
                        new
                        {
                            Id = 99,
                            Name = "Bär",
                            RecipesId = 22
                        },
                        new
                        {
                            Id = 100,
                            Name = "Keso",
                            RecipesId = 23
                        },
                        new
                        {
                            Id = 101,
                            Name = "Fiberhusk",
                            RecipesId = 23
                        },
                        new
                        {
                            Id = 102,
                            Name = "Ägg",
                            RecipesId = 23
                        },
                        new
                        {
                            Id = 103,
                            Name = "Smör",
                            RecipesId = 23
                        });
                });

            modelBuilder.Entity("MuskelMat_backend.Models.Recipes", b =>
                {
                    b.Property<int>("RecipesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kcal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Protein")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipesId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipesId = 1,
                            Kcal = 565,
                            MealType = "Lunch Middag",
                            Name = "Köttbullar i tomatsås med rostade grönsaker",
                            Protein = 28
                        },
                        new
                        {
                            RecipesId = 2,
                            Kcal = 625,
                            MealType = "Lunch Middag",
                            Name = "Kalkonfilépasta med paprikapesto",
                            Protein = 38
                        },
                        new
                        {
                            RecipesId = 3,
                            Kcal = 553,
                            MealType = "Lunch Middag",
                            Name = "Kotlett med äpple och ingefära",
                            Protein = 37
                        },
                        new
                        {
                            RecipesId = 4,
                            Kcal = 529,
                            MealType = "Lunch Middag",
                            Name = "Renskavsgryta med gröna ärtor",
                            Protein = 30
                        },
                        new
                        {
                            RecipesId = 5,
                            Kcal = 539,
                            MealType = "Lunch Middag",
                            Name = "Pitabröd med köttbullar och myntayoghurt",
                            Protein = 26
                        },
                        new
                        {
                            RecipesId = 6,
                            Kcal = 862,
                            MealType = "Lunch Middag",
                            Name = "Kebabspett med rödbetshummus",
                            Protein = 39
                        },
                        new
                        {
                            RecipesId = 7,
                            Kcal = 653,
                            MealType = "Lunch Middag",
                            Name = "Lövbiff med potatisgratäng och cosmopolitansallad",
                            Protein = 53
                        },
                        new
                        {
                            RecipesId = 8,
                            Kcal = 374,
                            MealType = "Lunch Middag",
                            Name = "Torsk i folie med linser, soltorkade tomater och basilika",
                            Protein = 36
                        },
                        new
                        {
                            RecipesId = 9,
                            Kcal = 419,
                            MealType = "Lunch Middag",
                            Name = "Pizza med varmrökt lax",
                            Protein = 27
                        },
                        new
                        {
                            RecipesId = 10,
                            Kcal = 504,
                            MealType = "Lunch Middag",
                            Name = "Ugnsbakad fisk med pepparrotsost",
                            Protein = 37
                        },
                        new
                        {
                            RecipesId = 11,
                            Kcal = 290,
                            MealType = "Frukost",
                            Name = "Kvarg med bär",
                            Protein = 45
                        },
                        new
                        {
                            RecipesId = 12,
                            Kcal = 424,
                            MealType = "Frukost",
                            Name = "Gröt med jordnötssmör och proteinpulver",
                            Protein = 29
                        },
                        new
                        {
                            RecipesId = 13,
                            Kcal = 906,
                            MealType = "Frukost",
                            Name = "Ägg & Bacon",
                            Protein = 57
                        },
                        new
                        {
                            RecipesId = 14,
                            Kcal = 339,
                            MealType = "Frukost",
                            Name = "Makrill och hackat ägg",
                            Protein = 30
                        },
                        new
                        {
                            RecipesId = 15,
                            Kcal = 593,
                            MealType = "Frukost",
                            Name = "Proteinpannkakor",
                            Protein = 49
                        },
                        new
                        {
                            RecipesId = 16,
                            Kcal = 533,
                            MealType = "Frukost",
                            Name = "Keso med äpple och kanel",
                            Protein = 60
                        },
                        new
                        {
                            RecipesId = 17,
                            Kcal = 610,
                            MealType = "Frukost",
                            Name = "Frukostdrink",
                            Protein = 63
                        },
                        new
                        {
                            RecipesId = 18,
                            Kcal = 389,
                            MealType = "Frukost",
                            Name = "Äggröra och kalkon",
                            Protein = 29
                        },
                        new
                        {
                            RecipesId = 19,
                            Kcal = 271,
                            MealType = "Mellanmål",
                            Name = "Proteinshake",
                            Protein = 36
                        },
                        new
                        {
                            RecipesId = 20,
                            Kcal = 80,
                            MealType = "Mellanmål",
                            Name = "Kokt ägg",
                            Protein = 7
                        },
                        new
                        {
                            RecipesId = 21,
                            Kcal = 52,
                            MealType = "Mellanmål",
                            Name = "Äpple",
                            Protein = 1
                        },
                        new
                        {
                            RecipesId = 22,
                            Kcal = 266,
                            MealType = "Mellanmål",
                            Name = "Keso med frukt och bär",
                            Protein = 29
                        },
                        new
                        {
                            RecipesId = 23,
                            Kcal = 157,
                            MealType = "Mellanmål",
                            Name = "Kesoplättar",
                            Protein = 18
                        });
                });

            modelBuilder.Entity("MuskelMat_backend.Models.Ingredients", b =>
                {
                    b.HasOne("MuskelMat_backend.Models.Recipes", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuskelMat_backend.Models.Recipes", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
